const DIM = { MD: 120, LG: 152, VIEWBOX: "0 0 120 40" };

export const APP_STORE_BUTTON_DIMENSIONS = {
    GOOGLE_PLAY: { WIDTH: DIM, HEIGHT: DIM, VIEWBOX: DIM.VIEWBOX },
    APP_STORE: { WIDTH: DIM, HEIGHT: DIM, VIEWBOX: DIM.VIEWBOX },
    APP_STORE_ALT: { WIDTH: DIM, HEIGHT: DIM, VIEWBOX: DIM.VIEWBOX },
    APP_STORE_ALT_2: { WIDTH: DIM, HEIGHT: DIM, VIEWBOX: DIM.VIEWBOX },
} as const;
