/**
 * Static LMS icons copied from extracted-portal (WP-00).
 * Use with <img src={LMS_ICONS.HOME} /> or Next Image.
 */
export const LMS_ICONS = {
    HOME: "/icons/home.svg",
    USER: "/icons/user.svg",
    USERS: "/icons/users.svg",
    TROPHY: "/icons/trophy.svg",
    STAR: "/icons/star.svg",
    STAR_OUTLINE: "/icons/star-outline.svg",
    BELL: "/icons/bell.svg",
    BOOK: "/icons/book.svg",
    BOOK_OPEN: "/icons/book-open.svg",
    CALENDAR: "/icons/calendar.svg",
    CHECK: "/icons/check.svg",
    CHECK_CIRCLE: "/icons/check-circle.svg",
    SEARCH: "/icons/search.svg",
    SETTINGS: "/icons/settings.svg",
    LOCK: "/icons/lock.svg",
    MAIL: "/icons/mail.svg",
    LOGOUT: "/icons/logout.svg",
    MENU: "/icons/menu.svg",
    CLOSE: "/icons/x.svg",
    PLUS: "/icons/plus.svg",
    MINUS: "/icons/minus.svg",
    CHEVRON_LEFT: "/icons/chevron-left.svg",
    CHEVRON_RIGHT: "/icons/chevron-right.svg",
    CHEVRON_DOWN: "/icons/chevron-down.svg",
    ARROW_LEFT: "/icons/arrow-left.svg",
    ARROW_RIGHT: "/icons/arrow-right.svg",
    MEDAL: "/icons/medal.svg",
    MEDAL_GOLD: "/icons/medal-gold.svg",
    GIFT: "/icons/gift.svg",
    GAMEPAD: "/icons/gamepad.svg",
    CHART: "/icons/chart.svg",
    CLIPBOARD: "/icons/clipboard.svg",
    TODO: "/icons/todo.svg",
    FLAG: "/icons/flag.svg",
    GLOBE: "/icons/globe.svg",
    GRADUATION: "/icons/graduation.svg",
    HEART: "/icons/heart.svg",
    INFO: "/icons/info.svg",
    SPARKLES: "/icons/sparkles.svg",
    ZAP: "/icons/zap.svg",
    TARGET: "/icons/target.svg",
    TREND_UP: "/icons/trend-up.svg",
    VIDEO: "/icons/video.svg",
    VOLUME: "/icons/volume.svg",
    SEND: "/icons/send.svg",
    REFRESH: "/icons/refresh.svg",
    UPLOAD: "/icons/upload.svg",
    DOWNLOAD: "/icons/download.svg",
    FOLDER: "/icons/folder.svg",
    FILE_TEXT: "/icons/file-text.svg",
    PENCIL: "/icons/pencil.svg",
    SHIELD: "/icons/shield.svg",
    CLOCK: "/icons/clock.svg",
    INBOX: "/icons/inbox.svg",
    MEGAPHONE: "/icons/megaphone.svg",
    LANGUAGES: "/icons/languages.svg",
    ROBOT: "/icons/robot.svg",
    BRAIN: "/icons/brain.svg",
    BULB: "/icons/bulb.svg",
    COMPASS: "/icons/compass.svg",
    WAVE: "/icons/wave.svg",
} as const;
