export const UI_TEXT = {
    common: {
        appName: "LMS Portal",
        loading: "Đang tải...",
        genericError: "Đã xảy ra lỗi. Vui lòng thử lại.",
        save: "Lưu",
        cancel: "Hủy",
        delete: "Xóa",
        close: "Đóng",
        noData: "Không có dữ liệu",
        today: "Hôm nay",
        password: {
            errors: {
                required: "Mật khẩu không được để trống",
                minLength: "Mật khẩu phải có ít nhất 6 ký tự",
                confirmRequired: "Xác nhận mật khẩu không được để trống",
                mismatch: "Mật khẩu xác nhận không khớp",
                weak: "Mật khẩu quá yếu",
            },
            hint: "Tối thiểu 6 ký tự, gồm chữ hoa, chữ thường và số",
        },
        closeModalWarning: {
            title: "Đóng form?",
            description: "Thay đổi chưa lưu sẽ bị mất.",
        },
        errors: {
            turnstileMissing: "Thiếu cấu hình Turnstile",
        },
        icons: {
            userAvatarAlt: "Ảnh đại diện",
            flagAlt: "Cờ",
            badgeAlt: "Huy hiệu",
        },
        symbols: {
            commandK: "⌘K",
            slash: "/",
            ellipsis: "...",
            copyright: "©",
        },
        time: {
            about: "khoảng",
            few: "vài",
        },
        actions: {
            edit: "Sửa",
            copyLink: "Sao chép liên kết",
            delete: "Xóa",
        },
        pagination: {
            page: "Trang",
            of: "của",
            previous: "Trước",
            next: "Sau",
            totalRecords: "Tổng bản ghi",
            perPage: "/trang",
            clickToChangePage: "Nhấn để đổi trang",
        },
        datePicker: {
            selectDate: "Chọn ngày",
            selectDates: "Chọn ngày",
            today: "Hôm nay",
            yesterday: "Hôm qua",
            thisWeek: "Tuần này",
            lastWeek: "Tuần trước",
            thisMonth: "Tháng này",
            lastMonth: "Tháng trước",
            thisYear: "Năm nay",
            lastYear: "Năm trước",
            allTime: "Tất cả",
            ariaLabel: "Chọn khoảng ngày",
            dash: "–",
            cancel: "Hủy",
            apply: "Áp dụng",
        },
        charts: {
            noData: "Không có dữ liệu biểu đồ",
        },
        richEditor: {
            bold: "In đậm",
            italic: "In nghiêng",
            underline: "Gạch chân",
            strike: "Gạch ngang",
            heading1: "Tiêu đề 1",
            heading2: "Tiêu đề 2",
            heading3: "Tiêu đề 3",
            bulletList: "Danh sách",
            orderedList: "Danh sách số",
            alignLeft: "Căn trái",
            alignCenter: "Căn giữa",
            alignRight: "Căn phải",
            justify: "Căn đều",
            quote: "Trích dẫn",
            codeBlock: "Khối mã",
            horizontalRule: "Đường kẻ",
            link: "Liên kết",
            image: "Hình ảnh",
            table: "Bảng",
            clearFormat: "Xóa định dạng",
            undo: "Hoàn tác",
            redo: "Làm lại",
            toggleHeaderRow: "Hàng tiêu đề",
            toggleHeaderColumn: "Cột tiêu đề",
            toggleHeaderCell: "Ô tiêu đề",
            addColumnBefore: "Thêm cột trước",
            addColumnAfter: "Thêm cột sau",
            deleteColumn: "Xóa cột",
            addRowBefore: "Thêm hàng trước",
            addRowAfter: "Thêm hàng sau",
            deleteRow: "Xóa hàng",
            mergeCells: "Gộp ô",
            splitCells: "Tách ô",
            deleteTable: "Xóa bảng",
        },
    },
    metadata: {
        layout: {
            titleDefault: "LMS Portal",
            description: "Nền tảng quản lý học tập",
            twitterTitle: "LMS Portal",
            twitterDescription: "Nền tảng quản lý học tập",
        },
        home: {
            description: "Chào mừng đến với LMS Portal",
        },
        login: {
            title: "Đăng nhập",
            description: "Đăng nhập vào LMS Portal",
        },
        forgotPassword: {
            title: "Quên mật khẩu",
            description: "Khôi phục mật khẩu",
        },
        resetPassword: {
            title: "Đặt lại mật khẩu",
            description: "Đặt lại mật khẩu mới",
        },
        otp: {
            title: "Xác thực OTP",
            description: "Nhập mã OTP được gửi đến email của bạn để hoàn tất đăng nhập.",
        },
    },
    home: {
        title: "LMS Portal",
        subtitle: "Nền tảng quản lý học tập — sẵn sàng để phát triển tính năng mới.",
        loginButton: "Đăng nhập",
    },
    layout: {
        menu: "Menu",
        logout: "Đăng xuất",
        loggingOut: "Đang đăng xuất...",
        adminSidebar: {
            logoAlt: "Rikkei Education Logo",
            adminSubtitle: "LMS · Quản trị viên",
        },
    },
    navigation: {
        home: "Trang chủ",
        login: "Đăng nhập",
    },
    auth: {
        splash: {
            headlineLine1: "Học viện lập trình",
            headlineLine2: "hoá thành hành trình game",
            subtitle: "Học theo lộ trình, chinh phục từng chặng, mở khoá kỹ năng & nghề nghiệp — biến việc học thành cuộc phiêu lưu.",
            startButton: "Bắt đầu →",
            featurePlay: "Học mà chơi",
            featurePath: "Lộ trình rõ ràng",
            featureAi: "AI đồng hành",
        },
        login: {
            title: "Quản lý đào tạo",
            welcomeBack: "Hệ thống - Quản lý đào tạo",
            emailLabel: "Email",
            emailPlaceholder: "Nhập email",
            passwordLabel: "Mật khẩu",
            passwordPlaceholder: "Nhập mật khẩu",
            submitButton: "Đăng nhập",
            submittingButton: "Đang đăng nhập…",
            forgotPassword: "Quên mật khẩu?",
            logoAlt: "RIKKEI Edu — where dreams come true",
            showPassword: "Hiện mật khẩu",
            hidePassword: "Ẩn mật khẩu",
            showPasswordLabel: "Hiện mật khẩu",
            hidePasswordLabel: "Ẩn mật khẩu",
            toasts: {
                successTitle: "Đăng nhập thành công",
                successDescription: "Chào mừng bạn quay trở lại!",
                errorTitle: "Đăng nhập thất bại",
                captchaRequiredTitle: "Vui lòng hoàn thành Captcha",
                captchaRequiredDesc: "Bạn cần xác minh danh tính trước khi đăng nhập.",
                otpSentTitle: "Mã OTP đã được gửi",
                otpSentDesc: "Vui lòng kiểm tra email để nhận mã xác thực.",
            },
            errors: {
                emailRequired: "Email không được để trống",
                emailInvalid: "Email không hợp lệ",
                loginFailed: "Email hoặc mật khẩu không đúng. Vui lòng thử lại.",
                tooManyRequests: "Tài khoản của bạn đang bị khóa do spam",
            },
        },
        register: {
            title: "Đăng ký",
            subtitle: "Tạo tài khoản mới",
            fullNameLabel: "Họ và tên",
            fullNamePlaceholder: "Nhập họ và tên",
            emailLabel: "Email",
            emailPlaceholder: "Nhập email",
            phoneLabel: "Số điện thoại",
            phonePlaceholder: "Nhập số điện thoại",
            passwordLabel: "Mật khẩu",
            passwordPlaceholder: "Nhập mật khẩu",
            confirmPasswordLabel: "Xác nhận mật khẩu",
            confirmPasswordPlaceholder: "Nhập lại mật khẩu",
            submitButton: "Đăng ký",
            hasAccount: "Đã có tài khoản?",
            loginLink: "Đăng nhập",
            errors: {
                fullNameRequired: "Họ và tên không được để trống",
                phoneNumberRequired: "Số điện thoại không được để trống",
                phoneNumberFormat: "Số điện thoại không hợp lệ",
                phoneNumberLength: "Số điện thoại phải có 10 chữ số",
                confirmPasswordRequired: "Xác nhận mật khẩu không được để trống",
                passwordMinLength: "Mật khẩu phải có ít nhất 6 ký tự",
                passwordsDoNotMatch: "Mật khẩu xác nhận không khớp",
            },
            successMessage: "Đăng ký thành công",
        },
        forgotPassword: {
            title: "Quên mật khẩu",
            subtitle: "Nhập email để nhận liên kết đặt lại mật khẩu",
            emailLabel: "Email",
            emailPlaceholder: "Nhập email",
            sendButton: "Gửi liên kết",
            backToLogin: "Quay lại đăng nhập",
            errors: {
                emailRequired: "Email không được để trống",
                emailInvalid: "Email không hợp lệ",
            },
            successModal: {
                title: "Kiểm tra email",
                message: "Nếu email tồn tại, chúng tôi đã gửi liên kết đặt lại mật khẩu.",
                buttonText: "Quay lại đăng nhập",
            },
        },
        resetPassword: {
            title: "Đặt lại mật khẩu",
            subtitle: "Nhập mật khẩu mới",
            passwordLabel: "Mật khẩu mới",
            passwordPlaceholder: "Nhập mật khẩu mới",
            confirmPasswordLabel: "Xác nhận mật khẩu",
            confirmPasswordPlaceholder: "Nhập lại mật khẩu",
            submitButton: "Đặt lại mật khẩu",
            backToLogin: "Quay lại đăng nhập",
            successMessage: "Đặt lại mật khẩu thành công",
            redirectMessage: "Đang chuyển đến trang đăng nhập...",
            showPasswordLabel: "Hiện mật khẩu",
            hidePasswordLabel: "Ẩn mật khẩu",
            errors: {
                tokenInvalid: "Liên kết đặt lại mật khẩu không hợp lệ",
                tokenExpired: "Liên kết đặt lại mật khẩu đã hết hạn",
            },
        },
        otp: {
            title: "Xác thực hai bước",
            subtitlePrefix: "Mã OTP đã được gửi đến email ",
            subtitleSuffix: ". Vui lòng kiểm tra và nhập mã bên dưới.",
            submitButton: "Xác nhận",
            submittingButton: "Đang xác thực...",
            resendPrefix: "Gửi lại mã sau ",
            resendSuffix: "s",
            resendButton: "Gửi lại mã OTP",
            backToLogin: "Quay lại trang Đăng nhập",
            loading: "Đang tải...",
            logoAlt: "Logo",
            expirePrefix: "Mã OTP sẽ hết hạn sau: ",
            toasts: {
                invalidOtpTitle: "Mã OTP không hợp lệ",
                invalidOtpDesc: "Vui lòng nhập đủ 6 chữ số.",
                successTitle: "Xác thực thành công",
                successDesc: "Chào mừng bạn đã đăng nhập hệ thống.",
                errorTitle: "Xác thực thất bại",
                resendInfoTitle: "Yêu cầu gửi lại mã",
                resendInfoDesc: "Vui lòng quay lại trang đăng nhập để gửi lại OTP.",
                resendErrorTitle: "Gửi lại thất bại",
                resendErrorDesc: "Không thể gửi lại OTP lúc này.",
                expiredTitle: "Mã OTP đã hết hạn",
                expiredDesc: "Vui lòng yêu cầu gửi lại mã OTP mới.",
            },
        },
    },
    errors: {
        title: "Đã xảy ra lỗi",
        somethingWentWrong: "Có lỗi xảy ra. Vui lòng thử lại.",
        retry: "Thử lại",
        forbiddenTitle: "Không có quyền truy cập",
        forbiddenDescription: "Bạn không có quyền truy cập trang này.",
        notFoundTitle: "Không tìm thấy trang",
        notFoundDescription: "Trang bạn tìm không tồn tại.",
        goHome: "Về trang chủ",
    },
    profile: {
        changePassword: {
            errors: {
                currentPasswordRequired: "Mật khẩu hiện tại không được để trống",
                newPasswordSameAsOld: "Mật khẩu mới phải khác mật khẩu hiện tại",
            },
        },
    },
    dateTimePicker: {
        today: "Hôm nay",
        time: "Thời gian",
        cancel: "Hủy",
        apply: "Áp dụng",
    },
    filter: {
        title: "Bộ lọc",
        condition: "Điều kiện",
        selectField: "Chọn trường",
        selectOperator: "Chọn toán tử",
        enterValue: "Nhập giá trị",
        addCondition: "Thêm điều kiện",
        clearFilters: "Xóa bộ lọc",
        apply: "Áp dụng",
        operators: {
            CONTAINS: "Chứa",
            NOT_CONTAINS: "Không chứa",
            EQUALS: "Bằng",
            NOT_EQUALS: "Khác",
            STARTS_WITH: "Bắt đầu bằng",
            ENDS_WITH: "Kết thúc bằng",
            IS_EMPTY: "Rỗng",
            IS_NOT_EMPTY: "Không rỗng",
            GREATER_THAN: "Lớn hơn",
            GREATER_THAN_OR_EQUAL: "Lớn hơn hoặc bằng",
            LESS_THAN: "Nhỏ hơn",
            LESS_THAN_OR_EQUAL: "Nhỏ hơn hoặc bằng",
            IN: "Thuộc",
            NOT_IN: "Không thuộc",
        },
        boolean: {
            true: "Đúng",
            false: "Sai",
        },
    },
    components: {
        editor: {
            mermaid: {
                title: "Mermaid",
                preview: "Xem trước",
                editCode: "Sửa mã",
                previewTitle: "Xem trước",
                editSource: "Sửa nguồn",
                copyCode: "Sao chép mã",
                editorModeHint: "Chỉnh sửa mã Mermaid bên dưới",
                syntaxError: "Lỗi cú pháp",
                fixErrorButton: "Sửa lỗi",
                emptyChart: "Biểu đồ trống",
                startWriting: "Bắt đầu viết mã Mermaid",
            },
        },
    },
    staff: {
        title: "Quản lý nhân viên",
        subtitle: "Danh sách tài khoản quản trị hệ thống và giảng viên",
        searchPlaceholder: "Tìm kiếm tên, email, sđt...",
        addStaff: "Thêm nhân viên",
        editStaff: "Sửa nhân viên",
        deleteStaff: "Xóa nhân viên",
        kpiTotal: "Tổng nhân viên",
        kpiTeachers: "Giảng viên / Trợ giảng",
        kpiActive: "Đang hoạt động",
        kpiAdmins: "Quản trị viên (Admin)",
        roleFilterAll: "Tất cả vai trò",
        statusFilterAll: "Tất cả trạng thái",
        statusActive: "Hoạt động",
        statusDisable: "Vô hiệu hóa",
        loading: "Đang tải danh sách nhân viên...",
        loadingSystems: "Đang tải danh sách hệ thống...",
        noDataTitle: "Không tìm thấy nhân viên nào",
        noDataDesc: "Thử thay đổi bộ lọc tìm kiếm hoặc thêm nhân viên mới.",

        // Table headers
        thStt: "STT",
        thAvatar: "Ảnh",
        thName: "Họ và tên",
        thContact: "SĐT / Email",
        thGender: "Giới tính",
        thAddress: "Địa chỉ",
        thRole: "Vai trò",
        thSystem: "Hệ đào tạo",
        thStatus: "Trạng thái",
        thActions: "Hành động",

        // Table values
        genderMale: "Nam",
        genderFemale: "Nữ",
        genderOther: "Khác",
        roleAdmin: "Quản trị viên",
        roleManager: "Quản lý",
        roleTeacher: "Giảng viên",
        roleTeacherAssistant: "Trợ giảng",
        roleAssistant: "Trợ lý",
        roleDefault: "Nhân viên",
        systemNone: "Không có",
        statusActiveLabel: "Hoạt động",
        statusDisableLabel: "Khóa",

        // Actions tooltips
        editTooltip: "Sửa thông tin",
        lockTooltip: "Vô hiệu hóa",
        unlockTooltip: "Kích hoạt",
        deleteTooltip: "Xóa tài khoản",

        // Add Staff Slideout
        addTitle: "Thêm nhân viên mới",
        addSubtitle: "Cấp tài khoản mới cho cán bộ, giảng viên của hệ thống.",
        labelFullName: "Họ và tên *",
        placeholderFullName: "Nhập họ và tên đầy đủ",
        labelEmail: "Email *",
        placeholderEmail: "Nhập địa chỉ email",
        labelPhone: "Số điện thoại *",
        placeholderPhone: "Nhập số điện thoại",
        labelAddress: "Địa chỉ *",
        placeholderAddress: "Nhập địa chỉ liên hệ",
        labelPassword: "Mật khẩu *",
        placeholderPassword: "Tạo mật khẩu đăng nhập",
        placeholderRoles: "Chọn vai trò...",
        labelGender: "Giới tính",
        placeholderGender: "Chọn giới tính",
        validationGender: "Vui lòng chọn giới tính",
        labelRoles: "Vai trò (Chọn nhiều) *",
        labelSystems: "Hệ đào tạo quản lý (Chọn nhiều)",
        labelWhitelist: "Miễn đăng nhập OTP (Whitelist)",
        descWhitelist: "Cho phép tài khoản đăng nhập trực tiếp không cần mã xác nhận email.",
        btnCancel: "Hủy bỏ",
        btnSave: "Lưu nhân viên",

        // Edit Staff Slideout
        editTitle: "Sửa thông tin nhân viên",
        editSubtitle: "Cập nhật thông tin chi tiết và phân quyền của cán bộ.",
        labelPasswordEdit: "Mật khẩu mới (Để trống nếu không đổi)",
        placeholderPasswordEdit: "Nhập mật khẩu mới từ 6 ký tự",
        btnUpdate: "Cập nhật",

        // Confirm Delete Modal
        confirmDeleteTitle: "Xóa tài khoản?",
        confirmDeleteMessage: "Bạn có chắc chắn muốn xóa vĩnh viễn tài khoản của nhân viên này? Hành động này không thể hoàn tác.",
        confirmDeleteBtn: "Xóa vĩnh viễn",
        confirmCancelBtn: "Hủy bỏ",

        // Notifications
        toastSuccess: "Thành công",
        toastError: "Lỗi",
        toastAddSuccess: "Đã thêm tài khoản nhân viên mới.",
        toastAddError: "Không thể tạo tài khoản nhân viên.",
        toastUpdateSuccess: "Đã cập nhật tài khoản nhân viên.",
        toastUpdateError: "Không thể cập nhật nhân viên.",
        toastDeleteSuccess: "Đã xóa tài khoản nhân viên.",
        toastDeleteError: "Không thể xóa nhân viên.",
    },
    trainingSystem: {
        title: "Quản lý Hệ đào tạo",
        subtitle: "Danh sách hệ đào tạo trong hệ thống lms",
        searchPlaceholder: "Tìm kiếm mã hệ, tên hệ...",
        addSystem: "Thêm hệ đào tạo",
        editSystem: "Sửa hệ đào tạo",
        deleteSystem: "Xóa hệ đào tạo",
        loading: "Đang tải danh sách hệ đào tạo...",
        noDataTitle: "Không tìm thấy hệ đào tạo nào",
        noDataDesc: "Thử thay đổi bộ lọc tìm kiếm hoặc thêm hệ đào tạo mới.",

        // Table headers
        thStt: "STT",
        thId: "Id hệ",
        thName: "Tên hệ",
        thCode: "Mã hệ",
        thCreatedAt: "Ngày tạo",
        thActions: "Hành động",

        // Actions/buttons
        viewDetails: "Xem chi tiết",
        learningPath: "Lộ trình học",
        deleteTooltip: "Xóa hệ đào tạo",

        // Add/Edit Modal
        addTitle: "Thêm hệ đào tạo mới",
        addSubtitle: "Tạo hệ đào tạo mới cho hệ thống quản lý.",
        editTitle: "Cập nhật hệ đào tạo",
        editSubtitle: "Chỉnh sửa mã và tên hệ đào tạo hiện tại.",
        labelCode: "Mã hệ đào tạo *",
        placeholderCode: "Nhập mã hệ đào tạo (VD: DT, EL, PK)",
        labelName: "Tên hệ đào tạo *",
        placeholderName: "Nhập tên hệ đào tạo đầy đủ",
        btnCancel: "Hủy bỏ",
        btnSave: "Lưu hệ đào tạo",
        btnUpdate: "Cập nhật",
        toastDetailsErrorDesc: "Không thể tải chi tiết chuyên ngành và kỳ học",
        loadingDetails: "Đang tải dữ liệu...",
        labelMajorsAndSemesters: "Chuyên ngành & Kỳ học",
        btnAddMajor: "Chuyên ngành",
        labelMajorIndexPrefix: "Chuyên ngành",
        btnHideSemesters: "Ẩn kỳ học",
        btnShowSemesters: "Hiện kỳ học",
        placeholderMajorName: "Nhập tên chuyên ngành...",
        deleteMajorTooltip: "Xóa chuyên ngành",
        placeholderSemesterName: "Nhập tên kỳ học...",
        deleteSemesterTooltip: "Xóa kỳ học",
        btnAddSemester: "Thêm kỳ học",

        // Confirm Delete Modal
        confirmDeleteTitle: "Xóa hệ đào tạo?",
        confirmDeleteMessage: "Bạn có chắc chắn muốn xóa vĩnh viễn hệ đào tạo này? Hành động này không thể hoàn tác.",
        confirmDeleteBtn: "Xóa vĩnh viễn",
        confirmCancelBtn: "Hủy bỏ",

        // Toasts
        toastSuccess: "Thành công",
        toastError: "Lỗi",
        toastAddSuccess: "Đã thêm hệ đào tạo mới thành công.",
        toastAddError: "Không thể thêm hệ đào tạo.",
        toastUpdateSuccess: "Đã cập nhật hệ đào tạo thành công.",
        toastUpdateError: "Không thể cập nhật hệ đào tạo.",
        toastDeleteSuccess: "Đã xóa hệ đào tạo thành công.",
        toastDeleteError: "Không thể xóa hệ đào tạo.",
        toastLearningPathPrefix: "Hệ đào tạo: ",
    },
    trainingTypesEl: {
        title: "Quản lý Hệ đào tạo",
        subtitle: "Danh sách hệ đào tạo trong hệ thống E-learning",
        searchPlaceholder: "Tìm kiếm tên hệ, chuyên ngành...",
        noData: "Không tìm thấy hệ đào tạo nào",
        thStt: "STT",
        thName: "Tên hệ",
        thMajors: "Chuyên ngành",
        thCreatedAt: "Ngày tạo",
        thActions: "Hành động",
        viewDetails: "Xem chi tiết",
        breadcrumbParent: "Quản lý E-Learning",
        breadcrumbTitle: "Hệ đào tạo",
        breadcrumbDetail: "Chi tiết",
        labelCode: "MÃ HỆ ĐÀO TẠO",
        labelName: "TÊN HỆ ĐÀO TẠO",
        labelCreatedAt: "NGÀY TẠO",
        searchSemestersPlaceholder: "Tìm kiếm kỳ học...",
        btnSort: "Sắp xếp",
        thId: "ID",
        thSemester: "Kỳ học",
        btnSubjectList: "Danh sách môn học",
        toastViewing: "Đang xem danh sách môn học của: ",
    },
    examsSetsEl: {
        title: "Quản lý Bộ đề trắc nghiệm",
        subtitle: "Danh sách bộ đề trắc nghiệm trong hệ thống E-learning",
        searchPlaceholder: "Tìm kiếm tên bộ đề...",
        noData: "Không tìm thấy bộ đề nào",
        thStt: "STT",
        thName: "Tên bộ đề",
        thCreatedAt: "Thời gian tạo",
        thActions: "Chức năng",
        viewDetails: "Xem chi tiết",
        editSet: "Sửa bộ đề",
        deleteSet: "Xóa bộ đề",
        questionsCountSuffix: " câu hỏi",
        breadcrumbParent: "Quản lý E-Learning",
        breadcrumbTitle: "Bộ đề trắc nghiệm",
        breadcrumbDetail: "Chi tiết",
        labelName: "Tên bộ đề",
        labelCode: "Mã bộ đề",
        labelCreatedAt: "Thời gian tạo",
        labelQuestionCount: "Số câu hỏi",
        tabQuiz: "Soạn câu hỏi Trắc nghiệm",
        tabEssay: "Soạn bài Tự luận",
        questionsHeader: "Danh sách câu hỏi trắc nghiệm",
        btnCreateQuestion: "Tạo câu hỏi mới",
        pointsSuffix: " điểm",
        essayMockContent: "Giao diện soạn bài tự luận của bộ đề",
        labelIdPrefix: "ID: ",
        separator: " | ",
        dotSeparator: ". ",
        modalAddTitle: "Thêm câu hỏi trắc nghiệm mới",
        modalEditTitle: "Sửa câu hỏi trắc nghiệm",
        labelQuestionTitle: "Tên / Tiêu đề câu hỏi *",
        placeholderQuestionTitle: "Ví dụ: Chọn định dạng đúng của IP Address",
        labelPoints: "Điểm số *",
        labelTotalPoints: "Tổng điểm bộ đề",
        labelQuestionDesc: "Nội dung câu hỏi",
        placeholderQuestionDesc: "Nhập nội dung văn bản...",
        labelAnswersList: "Danh sách câu trả lời (Click chọn câu trả lời đúng)",
        placeholderAnswer: "Nhập câu trả lời",
        labelCorrect: "Đúng",
        labelIncorrect: "Sai",
        btnSingleCorrect: "Câu trả lời đúng duy nhất",
        btnMultiCorrect: "Nhiều câu trả lời đúng",
        btnCancel: "Hủy bỏ",
        btnSave: "Lưu",
        toastQuestionAdded: "Đã thêm câu hỏi mới thành công.",
        toastQuestionUpdated: "Đã cập nhật câu hỏi thành công.",
        toastEssayQuestionAdded: "Đã thêm câu hỏi tự luận mới thành công.",
        toastEssayQuestionUpdated: "Đã cập nhật câu hỏi tự luận thành công.",
        toastEssayQuestionDeleted: "Đã xóa câu hỏi tự luận thành công.",
        labelEssayQuestionsList: "Danh sách câu hỏi tự luận",
        btnCreateEssayQuestion: "Tạo câu hỏi mới",
        labelNoEssayQuestions: "Chưa có câu hỏi tự luận nào",
        labelFunctionNamePrefix: "Hàm: ",
        labelInputPrefix: "Input: ",
        labelOutputPrefix: "Output: ",
        tooltipEditQuestion: "Sửa câu hỏi",
        tooltipDeleteQuestion: "Xóa câu hỏi",
        labelTestCasePrefix: "CASE ",
        labelNotAvailable: "n/a",
        richTextSource: "Nguồn",
        richTextParagraph: "Đoạn văn",
        richTextAi: "AI",
    },
} as const;
