export const UI_TEXT = {
    common: {
        appName: "LMS Portal",
        loading: "Đang tải...",
        genericError: "Đã xảy ra lỗi. Vui lòng thử lại.",
        save: "Lưu",
        cancel: "Hủy",
        delete: "Xóa",
        close: "Đóng",
        noData: "Không có dữ liệu",
        today: "Hôm nay",
        password: {
            errors: {
                required: "Mật khẩu không được để trống",
                minLength: "Mật khẩu phải có ít nhất 6 ký tự",
                confirmRequired: "Xác nhận mật khẩu không được để trống",
                mismatch: "Mật khẩu xác nhận không khớp",
                weak: "Mật khẩu quá yếu",
            },
            hint: "Tối thiểu 6 ký tự, gồm chữ hoa, chữ thường và số",
        },
        closeModalWarning: {
            title: "Đóng form?",
            description: "Thay đổi chưa lưu sẽ bị mất.",
        },
        errors: {
            turnstileMissing: "Thiếu cấu hình Turnstile",
        },
        icons: {
            userAvatarAlt: "Ảnh đại diện",
            flagAlt: "Cờ",
            badgeAlt: "Huy hiệu",
        },
        symbols: {
            commandK: "⌘K",
            slash: "/",
            ellipsis: "...",
            copyright: "©",
        },
        time: {
            about: "khoảng",
            few: "vài",
        },
        actions: {
            edit: "Sửa",
            copyLink: "Sao chép liên kết",
            delete: "Xóa",
        },
        pagination: {
            page: "Trang",
            of: "của",
            previous: "Trước",
            next: "Sau",
            totalRecords: "Tổng bản ghi",
            perPage: "/trang",
            clickToChangePage: "Nhấn để đổi trang",
        },
        datePicker: {
            selectDate: "Chọn ngày",
            selectDates: "Chọn ngày",
            today: "Hôm nay",
            yesterday: "Hôm qua",
            thisWeek: "Tuần này",
            lastWeek: "Tuần trước",
            thisMonth: "Tháng này",
            lastMonth: "Tháng trước",
            thisYear: "Năm nay",
            lastYear: "Năm trước",
            allTime: "Tất cả",
            ariaLabel: "Chọn khoảng ngày",
            dash: "–",
            cancel: "Hủy",
            apply: "Áp dụng",
        },
        charts: {
            noData: "Không có dữ liệu biểu đồ",
        },
        richEditor: {
            bold: "In đậm",
            italic: "In nghiêng",
            underline: "Gạch chân",
            strike: "Gạch ngang",
            heading1: "Tiêu đề 1",
            heading2: "Tiêu đề 2",
            heading3: "Tiêu đề 3",
            bulletList: "Danh sách",
            orderedList: "Danh sách số",
            alignLeft: "Căn trái",
            alignCenter: "Căn giữa",
            alignRight: "Căn phải",
            justify: "Căn đều",
            quote: "Trích dẫn",
            codeBlock: "Khối mã",
            horizontalRule: "Đường kẻ",
            link: "Liên kết",
            image: "Hình ảnh",
            table: "Bảng",
            clearFormat: "Xóa định dạng",
            undo: "Hoàn tác",
            redo: "Làm lại",
            toggleHeaderRow: "Hàng tiêu đề",
            toggleHeaderColumn: "Cột tiêu đề",
            toggleHeaderCell: "Ô tiêu đề",
            addColumnBefore: "Thêm cột trước",
            addColumnAfter: "Thêm cột sau",
            deleteColumn: "Xóa cột",
            addRowBefore: "Thêm hàng trước",
            addRowAfter: "Thêm hàng sau",
            deleteRow: "Xóa hàng",
            mergeCells: "Gộp ô",
            splitCells: "Tách ô",
            deleteTable: "Xóa bảng",
        },
    },
    metadata: {
        layout: {
            titleDefault: "LMS Portal",
            description: "Nền tảng quản lý học tập",
            twitterTitle: "LMS Portal",
            twitterDescription: "Nền tảng quản lý học tập",
        },
        home: {
            description: "Chào mừng đến với LMS Portal",
        },
        login: {
            title: "Đăng nhập",
            description: "Đăng nhập vào LMS Portal",
        },
        forgotPassword: {
            title: "Quên mật khẩu",
            description: "Khôi phục mật khẩu",
        },
        resetPassword: {
            title: "Đặt lại mật khẩu",
            description: "Đặt lại mật khẩu mới",
        },
        otp: {
            title: "Xác thực OTP",
            description: "Nhập mã OTP được gửi đến email của bạn để hoàn tất đăng nhập.",
        },
    },
    home: {
        title: "LMS Portal",
        subtitle: "Nền tảng quản lý học tập — sẵn sàng để phát triển tính năng mới.",
        loginButton: "Đăng nhập",
    },
    layout: {
        menu: "Menu",
        logout: "Đăng xuất",
        loggingOut: "Đang đăng xuất...",
        adminSidebar: {
            logoAlt: "Rikkei Education Logo",
            adminSubtitle: "LMS · Quản trị viên",
        },
    },
    navigation: {
        home: "Trang chủ",
        login: "Đăng nhập",
    },
    auth: {
        splash: {
            headlineLine1: "Học viện lập trình",
            headlineLine2: "hoá thành hành trình game",
            subtitle: "Học theo lộ trình, chinh phục từng chặng, mở khoá kỹ năng & nghề nghiệp — biến việc học thành cuộc phiêu lưu.",
            startButton: "Bắt đầu →",
            featurePlay: "Học mà chơi",
            featurePath: "Lộ trình rõ ràng",
            featureAi: "AI đồng hành",
        },
        login: {
            title: "Quản lý đào tạo",
            welcomeBack: "Hệ thống - Quản lý đào tạo",
            emailLabel: "Email",
            emailPlaceholder: "Nhập email",
            passwordLabel: "Mật khẩu",
            passwordPlaceholder: "Nhập mật khẩu",
            submitButton: "Đăng nhập",
            submittingButton: "Đang đăng nhập…",
            forgotPassword: "Quên mật khẩu?",
            logoAlt: "RIKKEI Edu — where dreams come true",
            showPassword: "Hiện mật khẩu",
            hidePassword: "Ẩn mật khẩu",
            showPasswordLabel: "Hiện mật khẩu",
            hidePasswordLabel: "Ẩn mật khẩu",
            toasts: {
                successTitle: "Đăng nhập thành công",
                successDescription: "Chào mừng bạn quay trở lại!",
                errorTitle: "Đăng nhập thất bại",
                captchaRequiredTitle: "Vui lòng hoàn thành Captcha",
                captchaRequiredDesc: "Bạn cần xác minh danh tính trước khi đăng nhập.",
                otpSentTitle: "Mã OTP đã được gửi",
                otpSentDesc: "Vui lòng kiểm tra email để nhận mã xác thực.",
                sessionExpired: "Phiên đăng nhập của bạn đã hết vui lòng đăng nhập lại",
            },
            errors: {
                emailRequired: "Email không được để trống",
                emailInvalid: "Email không hợp lệ",
                loginFailed: "Email hoặc mật khẩu không đúng. Vui lòng thử lại.",
                tooManyRequests: "Số lần đăng nhập quá nhiều, vui lòng thử lại sau 15 phút",
                captchaFailed: "Xác minh Captcha thất bại",
            },
        },
        register: {
            title: "Đăng ký",
            subtitle: "Tạo tài khoản mới",
            fullNameLabel: "Họ và tên",
            fullNamePlaceholder: "Nhập họ và tên",
            emailLabel: "Email",
            emailPlaceholder: "Nhập email",
            phoneLabel: "Số điện thoại",
            phonePlaceholder: "Nhập số điện thoại",
            passwordLabel: "Mật khẩu",
            passwordPlaceholder: "Nhập mật khẩu",
            confirmPasswordLabel: "Xác nhận mật khẩu",
            confirmPasswordPlaceholder: "Nhập lại mật khẩu",
            submitButton: "Đăng ký",
            hasAccount: "Đã có tài khoản?",
            loginLink: "Đăng nhập",
            errors: {
                fullNameRequired: "Họ và tên không được để trống",
                phoneNumberRequired: "Số điện thoại không được để trống",
                phoneNumberFormat: "Số điện thoại không hợp lệ",
                phoneNumberLength: "Số điện thoại phải có 10 chữ số",
                confirmPasswordRequired: "Xác nhận mật khẩu không được để trống",
                passwordMinLength: "Mật khẩu phải có ít nhất 6 ký tự",
                passwordsDoNotMatch: "Mật khẩu xác nhận không khớp",
            },
            successMessage: "Đăng ký thành công",
        },
        forgotPassword: {
            title: "Quên mật khẩu",
            subtitle: "Nhập email để nhận liên kết đặt lại mật khẩu",
            emailLabel: "Email",
            emailPlaceholder: "Nhập email",
            sendButton: "Gửi liên kết",
            backToLogin: "Quay lại đăng nhập",
            errors: {
                emailRequired: "Email không được để trống",
                emailInvalid: "Email không hợp lệ",
            },
            successModal: {
                title: "Kiểm tra email",
                message: "Nếu email tồn tại, chúng tôi đã gửi liên kết đặt lại mật khẩu.",
                buttonText: "Quay lại đăng nhập",
            },
        },
        resetPassword: {
            title: "Đặt lại mật khẩu",
            subtitle: "Nhập mật khẩu mới",
            passwordLabel: "Mật khẩu mới",
            passwordPlaceholder: "Nhập mật khẩu mới",
            confirmPasswordLabel: "Xác nhận mật khẩu",
            confirmPasswordPlaceholder: "Nhập lại mật khẩu",
            submitButton: "Đặt lại mật khẩu",
            backToLogin: "Quay lại đăng nhập",
            successMessage: "Đặt lại mật khẩu thành công",
            redirectMessage: "Đang chuyển đến trang đăng nhập...",
            showPasswordLabel: "Hiện mật khẩu",
            hidePasswordLabel: "Ẩn mật khẩu",
            errors: {
                tokenInvalid: "Liên kết đặt lại mật khẩu không hợp lệ",
                tokenExpired: "Liên kết đặt lại mật khẩu đã hết hạn",
            },
        },
        otp: {
            title: "Xác thực hai bước",
            subtitlePrefix: "Mã OTP đã được gửi đến email ",
            subtitleSuffix: ". Vui lòng kiểm tra và nhập mã bên dưới.",
            submitButton: "Xác nhận",
            submittingButton: "Đang xác thực...",
            resendPrefix: "Gửi lại mã sau ",
            resendSuffix: "s",
            resendButton: "Gửi lại mã OTP",
            backToLogin: "Quay lại trang Đăng nhập",
            loading: "Đang tải...",
            logoAlt: "Logo",
            expirePrefix: "Mã OTP sẽ hết hạn sau: ",
            toasts: {
                invalidOtpTitle: "Mã OTP không hợp lệ",
                invalidOtpDesc: "Vui lòng nhập đủ 6 chữ số.",
                successTitle: "Xác thực thành công",
                successDesc: "Chào mừng bạn đã đăng nhập hệ thống.",
                errorTitle: "Xác thực thất bại",
                resendInfoTitle: "Yêu cầu gửi lại mã",
                resendInfoDesc: "Vui lòng quay lại trang đăng nhập để gửi lại OTP.",
                resendErrorTitle: "Gửi lại thất bại",
                resendErrorDesc: "Không thể gửi lại OTP lúc này.",
                expiredTitle: "Mã OTP đã hết hạn",
                expiredDesc: "Vui lòng yêu cầu gửi lại mã OTP mới.",
            },
        },
    },
    errors: {
        title: "Đã xảy ra lỗi",
        somethingWentWrong: "Có lỗi xảy ra. Vui lòng thử lại.",
        retry: "Thử lại",
        forbiddenTitle: "Không có quyền truy cập",
        forbiddenDescription: "Bạn không có quyền truy cập trang này.",
        notFoundTitle: "Không tìm thấy trang",
        notFoundDescription: "Trang bạn tìm không tồn tại.",
        goHome: "Về trang chủ",
    },
    profile: {
        changePassword: {
            errors: {
                currentPasswordRequired: "Mật khẩu hiện tại không được để trống",
                newPasswordSameAsOld: "Mật khẩu mới phải khác mật khẩu hiện tại",
            },
        },
    },
    dateTimePicker: {
        today: "Hôm nay",
        time: "Thời gian",
        cancel: "Hủy",
        apply: "Áp dụng",
    },
    filter: {
        title: "Bộ lọc",
        condition: "Điều kiện",
        selectField: "Chọn trường",
        selectOperator: "Chọn toán tử",
        enterValue: "Nhập giá trị",
        addCondition: "Thêm điều kiện",
        clearFilters: "Xóa bộ lọc",
        apply: "Áp dụng",
        operators: {
            CONTAINS: "Chứa",
            NOT_CONTAINS: "Không chứa",
            EQUALS: "Bằng",
            NOT_EQUALS: "Khác",
            STARTS_WITH: "Bắt đầu bằng",
            ENDS_WITH: "Kết thúc bằng",
            IS_EMPTY: "Rỗng",
            IS_NOT_EMPTY: "Không rỗng",
            GREATER_THAN: "Lớn hơn",
            GREATER_THAN_OR_EQUAL: "Lớn hơn hoặc bằng",
            LESS_THAN: "Nhỏ hơn",
            LESS_THAN_OR_EQUAL: "Nhỏ hơn hoặc bằng",
            IN: "Thuộc",
            NOT_IN: "Không thuộc",
        },
        boolean: {
            true: "Đúng",
            false: "Sai",
        },
    },
    components: {
        editor: {
            mermaid: {
                title: "Mermaid",
                preview: "Xem trước",
                editCode: "Sửa mã",
                previewTitle: "Xem trước",
                editSource: "Sửa nguồn",
                copyCode: "Sao chép mã",
                editorModeHint: "Chỉnh sửa mã Mermaid bên dưới",
                syntaxError: "Lỗi cú pháp",
                fixErrorButton: "Sửa lỗi",
                emptyChart: "Biểu đồ trống",
                startWriting: "Bắt đầu viết mã Mermaid",
            },
        },
    },
    staff: {
        title: "Quản lý nhân viên",
        subtitle: "Danh sách tài khoản quản trị hệ thống và giảng viên",
        searchPlaceholder: "Tìm kiếm tên, email, sđt...",
        addStaff: "Thêm nhân viên",
        editStaff: "Sửa nhân viên",
        deleteStaff: "Xóa nhân viên",
        kpiTotal: "Tổng nhân viên",
        kpiTeachers: "Giảng viên / Trợ giảng",
        kpiActive: "Đang hoạt động",
        kpiAdmins: "Quản trị viên (Admin)",
        roleFilterAll: "Tất cả vai trò",
        statusFilterAll: "Tất cả trạng thái",
        statusActive: "Hoạt động",
        statusDisable: "Vô hiệu hóa",
        loading: "Đang tải danh sách nhân viên...",
        loadingSystems: "Đang tải danh sách hệ thống...",
        noDataTitle: "Không tìm thấy nhân viên nào",
        noDataDesc: "Thử thay đổi bộ lọc tìm kiếm hoặc thêm nhân viên mới.",

        // Table headers
        thStt: "STT",
        thAvatar: "Ảnh",
        thName: "Họ và tên",
        thContact: "SĐT / Email",
        thGender: "Giới tính",
        thAddress: "Địa chỉ",
        thRole: "Vai trò",
        thSystem: "Hệ đào tạo",
        thStatus: "Trạng thái",
        thActions: "Hành động",

        // Table values
        genderMale: "Nam",
        genderFemale: "Nữ",
        genderOther: "Khác",
        roleAdmin: "Quản trị viên",
        roleManager: "Quản lý",
        roleTeacher: "Giảng viên",
        roleTeacherAssistant: "Trợ giảng",
        roleAssistant: "Trợ lý",
        roleDefault: "Nhân viên",
        systemNone: "Không có",
        statusActiveLabel: "Hoạt động",
        statusDisableLabel: "Khóa",

        // Actions tooltips
        editTooltip: "Sửa thông tin",
        lockTooltip: "Vô hiệu hóa",
        unlockTooltip: "Kích hoạt",
        deleteTooltip: "Xóa tài khoản",

        // Add Staff Slideout
        addTitle: "Thêm nhân viên mới",
        addSubtitle: "Cấp tài khoản mới cho cán bộ, giảng viên của hệ thống.",
        labelFullName: "Họ và tên *",
        placeholderFullName: "Nhập họ và tên đầy đủ",
        labelEmail: "Email *",
        placeholderEmail: "Nhập địa chỉ email",
        labelPhone: "Số điện thoại *",
        placeholderPhone: "Nhập số điện thoại",
        labelAddress: "Địa chỉ *",
        placeholderAddress: "Nhập địa chỉ liên hệ",
        labelPassword: "Mật khẩu *",
        placeholderPassword: "Tạo mật khẩu đăng nhập",
        placeholderRoles: "Chọn vai trò...",
        labelGender: "Giới tính",
        placeholderGender: "Chọn giới tính",
        validationGender: "Vui lòng chọn giới tính",
        labelRoles: "Vai trò (Chọn nhiều) *",
        labelSystems: "Hệ đào tạo quản lý (Chọn nhiều)",
        labelWhitelist: "Miễn đăng nhập OTP (Whitelist)",
        descWhitelist: "Cho phép tài khoản đăng nhập trực tiếp không cần mã xác nhận email.",
        btnCancel: "Hủy bỏ",
        btnSave: "Lưu nhân viên",

        // Edit Staff Slideout
        editTitle: "Sửa thông tin nhân viên",
        editSubtitle: "Cập nhật thông tin chi tiết và phân quyền của cán bộ.",
        labelPasswordEdit: "Mật khẩu mới (Để trống nếu không đổi)",
        placeholderPasswordEdit: "Nhập mật khẩu mới từ 6 ký tự",
        btnUpdate: "Cập nhật",

        // Confirm Delete Modal
        confirmDeleteTitle: "Xóa tài khoản?",
        confirmDeleteMessage: "Bạn có chắc chắn muốn xóa vĩnh viễn tài khoản của nhân viên này? Hành động này không thể hoàn tác.",
        confirmDeleteBtn: "Xóa vĩnh viễn",
        confirmCancelBtn: "Hủy bỏ",

        // Notifications
        toastSuccess: "Thành công",
        toastError: "Lỗi",
        toastAddSuccess: "Đã thêm tài khoản nhân viên mới.",
        toastAddError: "Không thể tạo tài khoản nhân viên.",
        toastUpdateSuccess: "Đã cập nhật tài khoản nhân viên.",
        toastUpdateError: "Không thể cập nhật nhân viên.",
        toastDeleteSuccess: "Đã xóa tài khoản nhân viên.",
        toastDeleteError: "Không thể xóa nhân viên.",
    },
    trainingSystem: {
        title: "Quản lý Hệ đào tạo",
        subtitle: "Danh sách hệ đào tạo trong hệ thống lms",
        searchPlaceholder: "Tìm kiếm mã hệ, tên hệ...",
        addSystem: "Thêm hệ đào tạo",
        editSystem: "Sửa hệ đào tạo",
        deleteSystem: "Xóa hệ đào tạo",
        loading: "Đang tải danh sách hệ đào tạo...",
        noDataTitle: "Không tìm thấy hệ đào tạo nào",
        noDataDesc: "Thử thay đổi bộ lọc tìm kiếm hoặc thêm hệ đào tạo mới.",

        // Table headers
        thStt: "STT",
        thId: "Id hệ",
        thName: "Tên hệ",
        thCode: "Mã hệ",
        thCreatedAt: "Ngày tạo",
        thActions: "Hành động",

        // Actions/buttons
        viewDetails: "Xem chi tiết",
        learningPath: "Lộ trình học",
        deleteTooltip: "Xóa hệ đào tạo",

        // Add/Edit Modal
        addTitle: "Thêm hệ đào tạo mới",
        addSubtitle: "Tạo hệ đào tạo mới cho hệ thống quản lý.",
        editTitle: "Cập nhật hệ đào tạo",
        editSubtitle: "Chỉnh sửa mã và tên hệ đào tạo hiện tại.",
        labelCode: "Mã hệ đào tạo *",
        placeholderCode: "Nhập mã hệ đào tạo (VD: DT, EL, PK)",
        labelName: "Tên hệ đào tạo *",
        placeholderName: "Nhập tên hệ đào tạo đầy đủ",
        btnCancel: "Hủy bỏ",
        btnSave: "Lưu hệ đào tạo",
        btnUpdate: "Cập nhật",
        toastDetailsErrorDesc: "Không thể tải chi tiết chuyên ngành và kỳ học",
        loadingDetails: "Đang tải dữ liệu...",
        labelMajorsAndSemesters: "Chuyên ngành & Kỳ học",
        btnAddMajor: "Chuyên ngành",
        labelMajorIndexPrefix: "Chuyên ngành",
        btnHideSemesters: "Ẩn kỳ học",
        btnShowSemesters: "Hiện kỳ học",
        placeholderMajorName: "Nhập tên chuyên ngành...",
        deleteMajorTooltip: "Xóa chuyên ngành",
        placeholderSemesterName: "Nhập tên kỳ học...",
        deleteSemesterTooltip: "Xóa kỳ học",
        btnAddSemester: "Thêm kỳ học",

        // Confirm Delete Modal
        confirmDeleteTitle: "Xóa hệ đào tạo?",
        confirmDeleteMessage: "Bạn có chắc chắn muốn xóa vĩnh viễn hệ đào tạo này? Hành động này không thể hoàn tác.",
        confirmDeleteBtn: "Xóa vĩnh viễn",
        confirmCancelBtn: "Hủy bỏ",

        // Toasts
        toastSuccess: "Thành công",
        toastError: "Lỗi",
        toastAddSuccess: "Đã thêm hệ đào tạo mới thành công.",
        toastAddError: "Không thể thêm hệ đào tạo.",
        toastUpdateSuccess: "Đã cập nhật hệ đào tạo thành công.",
        toastUpdateError: "Không thể cập nhật hệ đào tạo.",
        toastDeleteSuccess: "Đã xóa hệ đào tạo thành công.",
        toastDeleteError: "Không thể xóa hệ đào tạo.",
        toastLearningPathPrefix: "Hệ đào tạo: ",
    },
    trainingTypesEl: {
        title: "Quản lý Hệ đào tạo",
        subtitle: "Danh sách hệ đào tạo trong hệ thống E-learning",
        searchPlaceholder: "Tìm kiếm tên hệ, chuyên ngành...",
        noData: "Không tìm thấy hệ đào tạo nào",
        thStt: "STT",
        thName: "Tên hệ",
        thMajors: "Chuyên ngành",
        thCreatedAt: "Ngày tạo",
        thActions: "Hành động",
        viewDetails: "Xem chi tiết",
        breadcrumbParent: "Quản lý E-Learning",
        breadcrumbTitle: "Hệ đào tạo",
        breadcrumbDetail: "Chi tiết",
        labelCode: "MÃ HỆ ĐÀO TẠO",
        labelName: "TÊN HỆ ĐÀO TẠO",
        labelCreatedAt: "NGÀY TẠO",
        searchCoursesPlaceholder: "Tìm kiếm môn học...",
        btnSort: "Sắp xếp",
        thId: "ID",
        thCourseCode: "Mã môn học",
        thCourseName: "Tên môn học",
        thHours: "Thời lượng",
        thDescription: "Mô tả",
        noCoursesData: "Hệ đào tạo này chưa có môn học nào",
        hours: "giờ",
    },
    examsSetsEl: {
        title: "Quản lý Bộ đề trắc nghiệm",
        subtitle: "Danh sách bộ đề trắc nghiệm trong hệ thống E-learning",
        searchPlaceholder: "Tìm kiếm tên bộ đề...",
        noData: "Không tìm thấy bộ đề nào",
        thStt: "STT",
        thName: "Tên bộ đề",
        thCreatedAt: "Thời gian tạo",
        thActions: "Chức năng",
        viewDetails: "Xem chi tiết",
        editSet: "Sửa bộ đề",
        deleteSet: "Xóa bộ đề",
        questionsCountSuffix: " câu hỏi",
        breadcrumbParent: "Quản lý E-Learning",
        breadcrumbTitle: "Bộ đề trắc nghiệm",
        breadcrumbDetail: "Chi tiết",
        labelName: "Tên bộ đề",
        labelCode: "Mã bộ đề",
        labelCreatedAt: "Thời gian tạo",
        labelQuestionCount: "Số câu hỏi",
        tabQuiz: "Soạn câu hỏi Trắc nghiệm",
        tabEssay: "Soạn bài Tự luận",
        questionsHeader: "Danh sách câu hỏi trắc nghiệm",
        btnCreateQuestion: "Tạo câu hỏi mới",
        pointsSuffix: " điểm",
        essayMockContent: "Giao diện soạn bài tự luận của bộ đề",
        labelIdPrefix: "ID: ",
        separator: " | ",
        dotSeparator: ". ",
        modalAddTitle: "Thêm câu hỏi trắc nghiệm mới",
        modalEditTitle: "Sửa câu hỏi trắc nghiệm",
        labelQuestionTitle: "Tên / Tiêu đề câu hỏi *",
        placeholderQuestionTitle: "Ví dụ: Chọn định dạng đúng của IP Address",
        labelPoints: "Điểm số *",
        labelTotalPoints: "Tổng điểm bộ đề",
        labelQuestionDesc: "Nội dung câu hỏi",
        placeholderQuestionDesc: "Nhập nội dung văn bản...",
        labelAnswersList: "Danh sách câu trả lời (Click chọn câu trả lời đúng)",
        placeholderAnswer: "Nhập câu trả lời",
        labelCorrect: "Đúng",
        labelIncorrect: "Sai",
        btnSingleCorrect: "Câu trả lời đúng duy nhất",
        btnMultiCorrect: "Nhiều câu trả lời đúng",
        btnCancel: "Hủy bỏ",
        btnSave: "Lưu",
        toastQuestionAdded: "Đã thêm câu hỏi mới thành công.",
        toastQuestionUpdated: "Đã cập nhật câu hỏi thành công.",
        toastEssayQuestionAdded: "Đã thêm câu hỏi tự luận mới thành công.",
        toastEssayQuestionUpdated: "Đã cập nhật câu hỏi tự luận thành công.",
        toastEssayQuestionDeleted: "Đã xóa câu hỏi tự luận thành công.",
        labelEssayQuestionsList: "Danh sách câu hỏi tự luận",
        btnCreateEssayQuestion: "Tạo câu hỏi mới",
        labelNoEssayQuestions: "Chưa có câu hỏi tự luận nào",
        labelFunctionNamePrefix: "Hàm: ",
        labelInputPrefix: "Input: ",
        labelOutputPrefix: "Output: ",
        tooltipEditQuestion: "Sửa câu hỏi",
        tooltipDeleteQuestion: "Xóa câu hỏi",
        labelTestCasePrefix: "CASE ",
        labelNotAvailable: "n/a",
        richTextSource: "Nguồn",
        richTextParagraph: "Đoạn văn",
        richTextAi: "AI",
    },
    studentManagement: {
        title: "Quản lý học viên",
        subtitle: "Danh sách và cấu hình thông tin học tập của học viên",
        searchPlaceholder: "Tìm theo họ tên...",
        studentCodePlaceholder: "Mã học viên...",
        allSystems: "Tất cả hệ học",
        allStatuses: "Tất cả trạng thái",
        importExcel: "Nhập Excel",
        addStudent: "Thêm học viên",
        editStudent: "Sửa học viên",
        deleteStudent: "Xóa học viên",
        noData: "Không tìm thấy học viên nào",
        thStudent: "Học viên",
        thContact: "Liên hệ",
        thLocation: "Cơ sở",
        thStatus: "Trạng thái",
        thActions: "Thao tác",
        avatarAlt: "Avatar",
        editTooltip: "Sửa thông tin",
        classTooltip: "Lớp học",
        deleteTooltip: "Xóa",
        toastSuccess: "Thành công",
        toastDeleteSuccess: "Đã xóa học viên",
        toastAddSuccess: "Đã thêm học viên mới",
        toastUpdateSuccess: "Đã cập nhật thông tin học viên",
        toastError: "Lỗi",
        toastDeleteError: "Không thể xóa học viên",
        toastImportSuccess: "Đã tải danh sách học viên từ file Excel",
        toastImportError: "Lỗi tệp dữ liệu",
        confirmDelete: "Bạn có chắc chắn muốn xóa học viên này?",
        modalAddTitle: "Thêm học viên mới",
        modalEditTitle: "Sửa học viên",
        labelFullName: "Họ và tên *",
        placeholderFullName: "Nguyễn Văn A",
        labelEmail: "Email *",
        placeholderEmail: "email@gmail.com",
        labelPhone: "Số điện thoại *",
        placeholderPhone: "098...",
        labelDateOfBirth: "Ngày sinh *",
        labelLocation: "Cơ sở đào tạo *",
        labelStudentCode: "Mã học viên (Tùy chọn)",
        placeholderStudentCode: "Tự sinh nếu rỗng",
        labelPassword: "Mật khẩu (Tùy chọn)",
        placeholderPassword: "Mặc định theo ngày sinh",
        labelStatus: "Trạng thái học tập *",
        labelSystems: "Hệ đào tạo liên kết *",
        importTitle: "Nhập học viên từ Excel",
        labelDefaultSystem: "Hệ đào tạo mặc định *",
        placeholderSystem: "Chọn hệ đào tạo...",
        dragDropHint: "Kéo thả tệp tin hoặc Click chọn",
        fileTypesHint: "Chỉ chấp nhận tệp .xlsx",
        selectedFilePrefix: "Đã chọn: ",
        resultTitle: "Kết quả Import:",
        resultInserted: "- Thêm mới: ",
        resultUpdated: "- Cập nhật hệ học: ",
        btnStartImport: "Bắt đầu tải lên",
        enrollModalTitle: "Quản lý lớp học của học viên",
        labelSelectClass: "Chọn lớp học *",
        placeholderClass: "Lớp học...",
        labelClassStatus: "Trạng thái *",
        btnEnroll: "Xếp lớp",
        activeLabel: "Active",
        classHistoryTitle: "Lớp học hiện tại",
        noClassEnrollment: "Chưa xếp vào lớp học nào",
        enrollDatePrefix: "Xếp lớp ngày: ",
    },
    courseClass: {
        title: "Phân công giảng dạy",
        subtitle: "Quản lý lớp học phần, gán giảng viên trợ giảng và môn học",
        listHeader: "Danh sách Lớp hành chính",
        detailsHeader: "Cấu hình Lớp học phần",
        detailsSub: "Gán môn học và giảng dạy",
        labelSubject: "Môn học *",
        placeholderSubject: "Chọn môn học...",
        labelTeacher: "Giảng viên *",
        placeholderTeacher: "Giảng viên...",
        labelTa: "Trợ giảng (Tùy chọn)",
        placeholderTa: "Trợ giảng...",
        labelStatus: "Trạng thái lớp phần *",
        labelStartDate: "Ngày bắt đầu",
        labelEndDate: "Ngày kết thúc",
        btnAssign: "Thêm phân công",
        assignedHeader: "Môn học đã phân công",
        noMapping: "Chưa có môn học học phần nào được phân công",
        classSelectHint: "Vui lòng chọn lớp hành chính ở thanh bên trái",
        toastMappingSuccess: "Đã phân công môn học & giảng viên vào lớp",
        toastDeleteSuccess: "Đã xóa phân công môn học",
    },
    learningMaterials: {
        title: "Quản lý Học liệu",
        subtitle: "Cấu hình chương trình học, buổi học, bài học và đính kèm học liệu",
        labelSystem: "Hệ đào tạo",
        placeholderSystem: "Chọn hệ...",
        coursesListHeader: "Danh sách môn học",
        curriculumHeader: "Khung chương trình học",
        curriculumSub: "Tạo buổi, bài học và gán tài liệu",
        btnSession: "Buổi học (Session)",
        btnLesson: "Bài học",
        noSession: "Chưa có buổi học nào",
        noLesson: "Không có bài học nào trong buổi này",
        courseSelectHint: "Vui lòng chọn môn học ở thanh lọc bên trái",
        promptSession: "Nhập tên buổi học mới (Session name):",
        promptLesson: "Nhập tên bài học mới (Lesson name):",
        toastSessionSuccess: "Đã thêm buổi học mới",
        toastLessonSuccess: "Đã thêm bài học mới",
        modalTitle: "Cấu hình học liệu",
        tabVideo: "Video bài học",
        tabReading: "Bài đọc (Markdown)",
        tabQuiz: "Bài tập kiểm tra (Quiz)",
        tabPreview: "Xem thử (Preview Player)",
        labelVideoFile: "Tải tệp Video (.mp4)",
        labelOr: "hoặc",
        labelVideoUrl: "Direct Link Video (e.g. YouTube, S3)",
        placeholderVideoUrl: "https://www.youtube.com/watch?v=...",
        labelDuration: "Thời lượng (giây)",
        questionsHeader: "Câu hỏi nhúng trắc nghiệm chặn dòng video",
        btnAddQuestion: "+ Thêm câu hỏi nhúng",
        labelQuestionContent: "Nội dung câu hỏi",
        labelTimeSeconds: "Thời điểm (s)",
        labelOptionsList: "Danh sách Đáp án",
        btnSaveVideo: "Lưu Video",
        toastSaveVideo: "Đã cập nhật video bài học",
        labelPdfFile: "Tải tệp PDF học liệu (.pdf)",
        labelReadingContent: "Nội dung bài viết (Markdown hoặc Rich Text)",
        placeholderReadingContent: "# Tiêu đề bài viết...",
        btnSaveReading: "Lưu Bài đọc",
        toastSaveReading: "Đã cập nhật bài đọc",
        labelSelectQuiz: "Chọn đề kiểm tra (Quiz)",
        placeholderQuiz: "Không có Quiz...",
        btnSaveQuiz: "Lưu Quiz Liên Kết",
        toastSaveQuiz: "Đã liên kết bài tập Quiz thành công",
        btnViewVideo: "Xem Video",
        btnViewReading: "Xem Bài đọc",
        btnViewQuiz: "Làm Quiz",
        labelLockQuestion: "Câu hỏi chặn màn hình",
        btnCheckAnswer: "Kiểm tra đáp án",
        feedbackCorrect: "Chính xác! Bạn có thể tiếp tục phát video.",
        feedbackIncorrect: "Chưa chính xác. Vui lòng thử lại!",
        labelTheoryContent: "Nội dung học lý thuyết",
        noTheoryContent: "Không có nội dung lý thuyết bằng văn bản.",
        labelReadingQuestions: "Câu hỏi kiểm tra bài đọc",
        labelQuizLinked: "QUIZ LINKED: ",
        labelQuizLinkedTitle: "Bài tập kiểm tra trắc nghiệm tổng hợp",
        labelQuizLinkedDesc: "Học viên sẽ được điều hướng qua trang thi trắc nghiệm riêng biệt để hoàn thành Quiz này.",
        btnStartQuiz: "Bắt đầu làm bài thi",
    },
} as const;
