export const UI_TEXT = {
    common: {
        appName: "LMS Portal",
        loading: "Đang tải...",
        genericError: "Đã xảy ra lỗi. Vui lòng thử lại.",
        save: "Lưu",
        cancel: "Hủy",
        delete: "Xóa",
        close: "Đóng",
        noData: "Không có dữ liệu",
        today: "Hôm nay",
        password: {
            errors: {
                required: "Mật khẩu không được để trống",
                minLength: "Mật khẩu phải có ít nhất 8 ký tự",
                confirmRequired: "Xác nhận mật khẩu không được để trống",
                mismatch: "Mật khẩu xác nhận không khớp",
                weak: "Mật khẩu quá yếu",
            },
            hint: "Tối thiểu 8 ký tự, gồm chữ hoa, chữ thường và số",
        },
        closeModalWarning: {
            title: "Đóng form?",
            description: "Thay đổi chưa lưu sẽ bị mất.",
        },
        errors: {
            turnstileMissing: "Thiếu cấu hình Turnstile",
        },
        icons: {
            userAvatarAlt: "Ảnh đại diện",
            flagAlt: "Cờ",
            badgeAlt: "Huy hiệu",
        },
        symbols: {
            commandK: "⌘K",
            slash: "/",
            ellipsis: "...",
            copyright: "©",
        },
        time: {
            about: "khoảng",
            few: "vài",
        },
        actions: {
            edit: "Sửa",
            copyLink: "Sao chép liên kết",
            delete: "Xóa",
        },
        pagination: {
            page: "Trang",
            of: "của",
            previous: "Trước",
            next: "Sau",
            totalRecords: "Tổng bản ghi",
            perPage: "/trang",
            clickToChangePage: "Nhấn để đổi trang",
        },
        datePicker: {
            selectDate: "Chọn ngày",
            selectDates: "Chọn ngày",
            today: "Hôm nay",
            yesterday: "Hôm qua",
            thisWeek: "Tuần này",
            lastWeek: "Tuần trước",
            thisMonth: "Tháng này",
            lastMonth: "Tháng trước",
            thisYear: "Năm nay",
            lastYear: "Năm trước",
            allTime: "Tất cả",
            ariaLabel: "Chọn khoảng ngày",
            dash: "–",
            cancel: "Hủy",
            apply: "Áp dụng",
        },
        charts: {
            noData: "Không có dữ liệu biểu đồ",
        },
        richEditor: {
            bold: "In đậm",
            italic: "In nghiêng",
            underline: "Gạch chân",
            strike: "Gạch ngang",
            heading1: "Tiêu đề 1",
            heading2: "Tiêu đề 2",
            heading3: "Tiêu đề 3",
            bulletList: "Danh sách",
            orderedList: "Danh sách số",
            alignLeft: "Căn trái",
            alignCenter: "Căn giữa",
            alignRight: "Căn phải",
            justify: "Căn đều",
            quote: "Trích dẫn",
            codeBlock: "Khối mã",
            horizontalRule: "Đường kẻ",
            link: "Liên kết",
            image: "Hình ảnh",
            table: "Bảng",
            clearFormat: "Xóa định dạng",
            undo: "Hoàn tác",
            redo: "Làm lại",
            toggleHeaderRow: "Hàng tiêu đề",
            toggleHeaderColumn: "Cột tiêu đề",
            toggleHeaderCell: "Ô tiêu đề",
            addColumnBefore: "Thêm cột trước",
            addColumnAfter: "Thêm cột sau",
            deleteColumn: "Xóa cột",
            addRowBefore: "Thêm hàng trước",
            addRowAfter: "Thêm hàng sau",
            deleteRow: "Xóa hàng",
            mergeCells: "Gộp ô",
            splitCells: "Tách ô",
            deleteTable: "Xóa bảng",
        },
    },
    metadata: {
        layout: {
            titleDefault: "LMS Portal",
            description: "Nền tảng quản lý học tập",
            twitterTitle: "LMS Portal",
            twitterDescription: "Nền tảng quản lý học tập",
        },
        home: {
            description: "Chào mừng đến với LMS Portal",
        },
        login: {
            title: "Đăng nhập",
            description: "Đăng nhập vào LMS Portal",
        },
        forgotPassword: {
            title: "Quên mật khẩu",
            description: "Khôi phục mật khẩu",
        },
        resetPassword: {
            title: "Đặt lại mật khẩu",
            description: "Đặt lại mật khẩu mới",
        },
        otp: {
            title: "Xác thực OTP",
            description: "Nhập mã OTP được gửi đến email của bạn để hoàn tất đăng nhập.",
        },
    },
    home: {
        title: "LMS Portal",
        subtitle: "Nền tảng quản lý học tập — sẵn sàng để phát triển tính năng mới.",
        loginButton: "Đăng nhập",
    },
    layout: {
        menu: "Menu",
        logout: "Đăng xuất",
        loggingOut: "Đang đăng xuất...",
        adminSidebar: {
            logoAlt: "Rikkei Education Logo",
            adminSubtitle: "LMS · Quản trị viên",
        },
    },
    navigation: {
        home: "Trang chủ",
        login: "Đăng nhập",
    },
    auth: {
        splash: {
            headlineLine1: "Học viện lập trình",
            headlineLine2: "hoá thành hành trình game",
            subtitle: "Học theo lộ trình, chinh phục từng chặng, mở khoá kỹ năng & nghề nghiệp — biến việc học thành cuộc phiêu lưu.",
            startButton: "Bắt đầu →",
            featurePlay: "Học mà chơi",
            featurePath: "Lộ trình rõ ràng",
            featureAi: "AI đồng hành",
        },
        login: {
            title: "Đăng nhập",
            welcomeBack: "Chào mừng bạn quay lại hành trình học",
            emailLabel: "Email",
            emailPlaceholder: "Nhập email",
            passwordLabel: "Mật khẩu",
            passwordPlaceholder: "Nhập mật khẩu",
            submitButton: "Đăng nhập",
            submittingButton: "Đang đăng nhập…",
            forgotPassword: "Quên mật khẩu?",
            logoAlt: "RIKKEI Edu — where dreams come true",
            showPassword: "Hiện mật khẩu",
            hidePassword: "Ẩn mật khẩu",
            showPasswordLabel: "Hiện mật khẩu",
            hidePasswordLabel: "Ẩn mật khẩu",
            toasts: {
                successTitle: "Đăng nhập thành công",
                successDescription: "Chào mừng bạn quay trở lại!",
                errorTitle: "Đăng nhập thất bại",
                captchaRequiredTitle: "Vui lòng hoàn thành Captcha",
                captchaRequiredDesc: "Bạn cần xác minh danh tính trước khi đăng nhập.",
                otpSentTitle: "Mã OTP đã được gửi",
                otpSentDesc: "Vui lòng kiểm tra email để nhận mã xác thực.",
            },
            errors: {
                emailRequired: "Email không được để trống",
                emailInvalid: "Email không hợp lệ",
                loginFailed: "Email hoặc mật khẩu không đúng. Vui lòng thử lại.",
            },
        },
        register: {
            title: "Đăng ký",
            subtitle: "Tạo tài khoản mới",
            fullNameLabel: "Họ và tên",
            fullNamePlaceholder: "Nhập họ và tên",
            emailLabel: "Email",
            emailPlaceholder: "Nhập email",
            phoneLabel: "Số điện thoại",
            phonePlaceholder: "Nhập số điện thoại",
            passwordLabel: "Mật khẩu",
            passwordPlaceholder: "Nhập mật khẩu",
            confirmPasswordLabel: "Xác nhận mật khẩu",
            confirmPasswordPlaceholder: "Nhập lại mật khẩu",
            submitButton: "Đăng ký",
            hasAccount: "Đã có tài khoản?",
            loginLink: "Đăng nhập",
            errors: {
                fullNameRequired: "Họ và tên không được để trống",
                phoneNumberRequired: "Số điện thoại không được để trống",
                phoneNumberFormat: "Số điện thoại không hợp lệ",
                phoneNumberLength: "Số điện thoại phải có 10 chữ số",
                confirmPasswordRequired: "Xác nhận mật khẩu không được để trống",
                passwordMinLength: "Mật khẩu phải có ít nhất 8 ký tự",
                passwordsDoNotMatch: "Mật khẩu xác nhận không khớp",
            },
            successMessage: "Đăng ký thành công",
        },
        forgotPassword: {
            title: "Quên mật khẩu",
            subtitle: "Nhập email để nhận liên kết đặt lại mật khẩu",
            emailLabel: "Email",
            emailPlaceholder: "Nhập email",
            sendButton: "Gửi liên kết",
            backToLogin: "Quay lại đăng nhập",
            errors: {
                emailRequired: "Email không được để trống",
                emailInvalid: "Email không hợp lệ",
            },
            successModal: {
                title: "Kiểm tra email",
                message: "Nếu email tồn tại, chúng tôi đã gửi liên kết đặt lại mật khẩu.",
                buttonText: "Quay lại đăng nhập",
            },
        },
        resetPassword: {
            title: "Đặt lại mật khẩu",
            subtitle: "Nhập mật khẩu mới",
            passwordLabel: "Mật khẩu mới",
            passwordPlaceholder: "Nhập mật khẩu mới",
            confirmPasswordLabel: "Xác nhận mật khẩu",
            confirmPasswordPlaceholder: "Nhập lại mật khẩu",
            submitButton: "Đặt lại mật khẩu",
            backToLogin: "Quay lại đăng nhập",
            successMessage: "Đặt lại mật khẩu thành công",
            redirectMessage: "Đang chuyển đến trang đăng nhập...",
            showPasswordLabel: "Hiện mật khẩu",
            hidePasswordLabel: "Ẩn mật khẩu",
            errors: {
                tokenInvalid: "Liên kết đặt lại mật khẩu không hợp lệ",
                tokenExpired: "Liên kết đặt lại mật khẩu đã hết hạn",
            },
        },
        otp: {
            title: "Xác thực hai bước",
            subtitlePrefix: "Mã OTP đã được gửi đến email ",
            subtitleSuffix: ". Vui lòng kiểm tra và nhập mã bên dưới.",
            submitButton: "Xác nhận",
            submittingButton: "Đang xác thực...",
            resendPrefix: "Gửi lại mã sau ",
            resendSuffix: "s",
            resendButton: "Gửi lại mã OTP",
            backToLogin: "Quay lại trang Đăng nhập",
            loading: "Đang tải...",
            logoAlt: "Logo",
            toasts: {
                invalidOtpTitle: "Mã OTP không hợp lệ",
                invalidOtpDesc: "Vui lòng nhập đủ 6 chữ số.",
                successTitle: "Xác thực thành công",
                successDesc: "Chào mừng bạn đã đăng nhập hệ thống.",
                errorTitle: "Xác thực thất bại",
                resendInfoTitle: "Yêu cầu gửi lại mã",
                resendInfoDesc: "Vui lòng quay lại trang đăng nhập để gửi lại OTP.",
                resendErrorTitle: "Gửi lại thất bại",
                resendErrorDesc: "Không thể gửi lại OTP lúc này.",
            },
        },
    },
    errors: {
        title: "Đã xảy ra lỗi",
        somethingWentWrong: "Có lỗi xảy ra. Vui lòng thử lại.",
        retry: "Thử lại",
        forbiddenTitle: "Không có quyền truy cập",
        forbiddenDescription: "Bạn không có quyền truy cập trang này.",
        notFoundTitle: "Không tìm thấy trang",
        notFoundDescription: "Trang bạn tìm không tồn tại.",
        goHome: "Về trang chủ",
    },
    profile: {
        changePassword: {
            errors: {
                currentPasswordRequired: "Mật khẩu hiện tại không được để trống",
                newPasswordSameAsOld: "Mật khẩu mới phải khác mật khẩu hiện tại",
            },
        },
    },
    dateTimePicker: {
        today: "Hôm nay",
        time: "Thời gian",
        cancel: "Hủy",
        apply: "Áp dụng",
    },
    filter: {
        title: "Bộ lọc",
        condition: "Điều kiện",
        selectField: "Chọn trường",
        selectOperator: "Chọn toán tử",
        enterValue: "Nhập giá trị",
        addCondition: "Thêm điều kiện",
        clearFilters: "Xóa bộ lọc",
        apply: "Áp dụng",
        operators: {
            CONTAINS: "Chứa",
            NOT_CONTAINS: "Không chứa",
            EQUALS: "Bằng",
            NOT_EQUALS: "Khác",
            STARTS_WITH: "Bắt đầu bằng",
            ENDS_WITH: "Kết thúc bằng",
            IS_EMPTY: "Rỗng",
            IS_NOT_EMPTY: "Không rỗng",
            GREATER_THAN: "Lớn hơn",
            GREATER_THAN_OR_EQUAL: "Lớn hơn hoặc bằng",
            LESS_THAN: "Nhỏ hơn",
            LESS_THAN_OR_EQUAL: "Nhỏ hơn hoặc bằng",
            IN: "Thuộc",
            NOT_IN: "Không thuộc",
        },
        boolean: {
            true: "Đúng",
            false: "Sai",
        },
    },
    components: {
        editor: {
            mermaid: {
                title: "Mermaid",
                preview: "Xem trước",
                editCode: "Sửa mã",
                previewTitle: "Xem trước",
                editSource: "Sửa nguồn",
                copyCode: "Sao chép mã",
                editorModeHint: "Chỉnh sửa mã Mermaid bên dưới",
                syntaxError: "Lỗi cú pháp",
                fixErrorButton: "Sửa lỗi",
                emptyChart: "Biểu đồ trống",
                startWriting: "Bắt đầu viết mã Mermaid",
            },
        },
    },
} as const;
